Update README.md
Appliscale/cloud-security-audit pull request #49
Opened 2019-01-16 11:42 UTC by maxiwoj

2019-01-16 11:56 UTC, SylwiaGargula submitted a review, later dismissed

2019-01-16 11:57 UTC, pfigwer requested changes

2019-01-16 11:57 UTC, pfigwer commented on README.md
> +Then build and install configuration for the application inside clous-security-audit directory by executing:
clouD-security-audit

2019-01-17 09:42 UTC, maxiwoj commented on README.md
> +Then build and install configuration for the application inside clous-security-audit directory by executing:
Damn, takie krótkie a z błędem

2019-01-17 09:43 UTC, pfigwer approved these changes

2019-01-17 09:45 UTC, merged